### ISSUE TITLE
Unable to "Sign In"

### ISSUE THREAD

**Issue by ginginsha** [scratchrealm/kachery-cloud#2]
I'm unable to sign in / sign up using both the CLI and the Python interface when initializing.
When I attempt to do so, an authentication screen will appear for a second and then disappear without feedback.

![Screenshot from 2022-05-12 11-31-01](https://user-images.githubusercontent.com/9399479/168112782-f4d3368c-3663-45a2-bef2-a3ee3d4a871a.png)

**Comment by magland** [comment]
Which browser are you using? We have been developing/testing using chrome.

**Comment by ginginsha** [comment]
I'm using Chrome as well.

**Comment by magland** [comment]
So when you click on the "sign in" button on the website, you get the auth window pop up and then disappear? That's strange, I haven't seen that. I wonder if there's a pop-up blocker interering? What operating system?
